# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY client.py data_owner_client.py  


RUN pip install --no-cache-dir <your-dependencies>

# Define environment variable
ENV CLIENT_TYPE=dataowner

# Run client.py when the container launches
CMD ["python", "client.py"]